AC-1716: Handle application version uninstall
AI4VBH/AIDE-front-end pull request #137
Opened 2023-04-11 14:16 UTC by mehranrashid

### Description

Uninstalls application version

Fixes  [AC-1716](https://answerconsulting.jira.com/browse/AC-1716).

If the application version status is set to active, the uninstall button is disabled
![image](https://user-images.githubusercontent.com/78732510/231191204-f01f0e6d-56f6-409b-a7bf-00ecb65aae42.png)

If the application version is not set to active and is not referenced in another workflow, allow uninstall
[uninstall.webm](https://user-images.githubusercontent.com/78732510/231191406-6505d00f-1413-4f8b-b9b6-de7e65ac5d68.webm)

If the application version is not set to active but is referenced in another workflow, do not allow uninstall and display what workflows it is referenced in. Allow user to navigate to workflow editor
[cannot-uninstall.webm](https://user-images.githubusercontent.com/78732510/231191582-bd48299d-205f-4629-a517-61d341eb7b73.webm)

Modal is also scrollable
![image](https://user-images.githubusercontent.com/78732510/231191686-63fded8a-0744-4c4a-a7a2-e436cb3dc87d.png)

### Status
**Ready**

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New unit tests added to cover the changes.
- [ ] New e2e tests added to cover the changes. (If it has been decided these will not be added with the PR, a separate ticket **must** be created and linked in the ticket below before merge)
- [x] All tests passed locally.

2023-04-13 07:48 UTC, rowellx68 approved these changes

2023-04-13 11:18 UTC, RemakingEden requested changes

2023-04-13 11:18 UTC, RemakingEden commented on cypress/e2e/workflows_test.cy.ts
> +describe("Workflow editor - navigating directly via URL", () => {
I believe the way we are writing these the describe block would give info for a whole bunch of tests and then the granular info should be in the it block. Perhaps this describe should be a little more generic.

2023-04-13 13:15 UTC, mehranrashid commented on cypress/e2e/workflows_test.cy.ts
> +describe("Workflow editor - navigating directly via URL", () => {
Changed to simply `Workflow editor`

2023-04-14 08:01 UTC, RemakingEden approved these changes
LGTM

2023-04-14 08:57 UTC, merged