AC-2217 fix issue with changing date resetting workflow and task on dashboard
AI4VBH/AIDE-front-end pull request #184
Opened 2023-05-15 16:51 UTC by lillie-dae

### Description

Fixes # .

A few sentences describing the changes proposed in this pull request.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New unit tests added to cover the changes.
- [ ] New e2e tests added to cover the changes. (If it has been decided these will not be added with the PR, a separate ticket **must** be created and linked in the ticket below before merge)
- [ ] All tests passed locally.

2023-05-15 19:32 UTC, JoeBatt1989 approved these changes

2023-05-16 08:16 UTC, JoeBatt1989 requested changes
@lillie-dae it looks like this is fixed now, someone must have done it as part of another bug

2023-05-16 08:20 UTC, JoeBatt1989 approved these changes

2023-05-16 08:31 UTC, DanielNuttall-AD approved these changes

2023-05-16 08:31 UTC, merged